import { Inter } from "next/font/google";
import "./globals.css";
import { SWRProvider } from "./swr-provider";
import Nav1 from '@/componets/Navbar';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SWRProvider>
          <Nav1/>
          {children}</SWRProvider>
      </body>
    </html>
  );
}
